- src/Database/Dongle.php
If column has number type, it needs cast to string
> Fix error with numeric concatination in PostgreSQL

- src/Database/DataFeed.php
We can not to quote class name with slashes, when using sqlite, because we will see an error like
Class 'Autor\\Plugin\\Models\\Model' not found
But, when we use mysql, we need use str_replace, or we will see another error
Class 'AutorPluginModelsModel' not found
So, I think we can check the config of connection to prevent this error.
> Turn off the quoting class name with slashes, when use sqlite

- src/Database/Attach/File.php
If the physical file doesn't exist in the disk, but the file record is still in the database, getThumb produced no error at all, but the whole PHP execution just stop.
> File->getThumb just halt without any error returned

- src/Database/Traits/Hashable.php
I need to add a hashable attribute to the backend users model but the hashable array is protected. Figured I'd add a method to allow plugins to add hashable fields.
> Let plugins add hashable fields

- src/Database/Traits/Validation.php
This PR adds support for an `attributeNames` model property which the *Validation* trait uses to display better attribute names in error messages.
In your model:
```php
public $attributeNames = ['my_attrib' => 'My Attrib Name'];
```
Based on [this Ardent PR](https://github.com/laravelbook/ardent/pull/213/files). Keeps support for localization that was already present. Order of priority is explicitly passed, model property, localization file.
> Add settable attributeNames array for use in validation trait

- src/Auth/Models/User.php
Requires merging of https://github.com/octobercms/library/pull/65 first.
I want to extend backend user profile form with a plugin however I can't set custom messages or the new attribute names lists because they're not explicitly set in any of the models so I can't, for instance, do:
```php
\Backend\Models\User::extend(function($model) {
$model->attributeNames['mfa_answer_2'] = 'Security Answer 2';
});
```
> Add validation attribs for auth model

- src/Database/Traits/Validation.php
Validation doesn't work with Encryptable trait. It validate every field after encryption. For example I have field name with rule 'between:3,35', but after encryption name is something like that:
'eyJpdiI6IlRZeUZWQ25JU3JCelZEUjVuXC9rV3RRPT0iLCJ2YWx1ZSI6Ik9iK24rajFvZUh6QVhLZ1RLRWpGeFE9PSIsIm1hYyI6ImE5ODhmY2E3YTA1NGZjNDNhN2VlYjA5YmQxNGQxMjY1NzUzMzYxZGUwZjg0NDQ5YjljYzUzYjJjNjkzOTk2MGQifQ=='
That's for sure longer then 35 chars.
> Validate original values before encryption

- src/Html/UrlGenerator.php
`URL::full()` is currently bugged due to a call to a property that doesn't exist.
> Use correct class property

- src/Database/NestedTreeScope.php
Using *NestedTree* trait results in the error
> Declaration of October\Rain\Database\NestedTreeScope::apply() must be compatible with Illuminate\Database\Eloquent\ScopeInterface::apply(Illuminate\Database\Eloquent\Builder $builder, Illuminate\Database\Eloquent\Model $model)
You were missing the `$model` argument on the apply/remove methods.
> Fix declaration incompatibility error

- src/Database/Model.php
Models currently have a `dates` property that converts date attributes to carbon objects but [it's protected](https://github.com/octobercms/library/blob/master/src/Database/Model.php#L54) so plugins can't add carbon date fields. This PR adds a simple adder method to make this possible.
> Add addDateAttribute method

- src/Mail/Mailer.php
In Laravel 5, the Mailer's send method returns the response, which can be useful when using services like Mandrill.
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Mail/Mailer.php#L166
> Updated Mailer so that it returns the response

- src/Database/Attach/File.php
When uploading a file to a cloud storage, set the visibility automatically based on the model config.
> Set file visibility in cloud storage

- src/Exception/ExceptionBase.php
For example, place this faulty line anywhere in Your code:
echo abc;
Expected output: exception page
Current output: blank white page with no information
> Fixed exceptions not being out-put in case of wrong PHP syntax

- src/Database/Model.php
Wrap single model in array instead of casting which creates array of all model fields, meaning push will fail.
> Wrap single model in array in push(), fixes #1067 in octobercms/october

- src/Database/Relations/HasOneOrMany.php
As per issue #103 , adds saveMany implementation to align with other October specific persistance methods.
Not sure if the deferred binding will work if a $sessionKey is passed, as the $models you pass in saveMany tend to not have been saved yet, meaning the call to bindDeferred wouldn't have an ID to write to the table, but I guess that's a separate issue. 
One possible solution to this could be in the save method of the HasOneOrMany trait, to save the $model before calling $this->add() maybe?
> add October specific implementation of ->saveMany(), references #103

- src/Database/Model.php
You have the `in_array` arguments in `addDateAttribute` method around the wrong way resulting in the error *in_array() expects parameter 2 to be array, string given* when called.
> Fix in_array argument order

- src/Database/Models/DeferredBinding.php
The where clauses where firing SQL Exceptions because of bad syntax.
> Fix cancelDeferredActions query

- src/Database/Model.php
- src/Database/Traits/Validation.php
This PR try to fix the validation of array values.
When defining a $rule for a model's jsonable attribute value, it was not unserializing before the validation occur.
For this I had to make Model::jsonable read public with getJsonable() method.
> fix for validation of array values

- src/Auth/Manager.php
The translation doesn't work because the use of `Exception` instead of `AuthException` in `Auth::authenticate`
> Change Exception to AuthException

- src/Router/Rule.php
- tests/Router/RouterTest.php
* I have a CMS Page with slug `blog/:slug*` 
* I hit the URL `/blog/foo` in my browser
* I call `$this->param('slug')` in my component `onRun` method and get *foo/*
I should be getting *foo*. No other param wildcard or otherwise has a */* suffix.
This issue only occurs when you hit a wildcard segment with a single URL segment. For example if I hit the URL `/blog/foo/bar` then `$this->param('slug')` will correctly return *foo/bar*.
My PR includes new tests to cover this.
> Remove unwanted / suffix from single wildcard segments

- src/Database/Model.php
The __call method's second parameter, here called `$params`, is required and will always be present as an array (http://www.php.net/manual/en/language.oop5.overloading.php#object.call), adding a default value (like `$params = null`) is not needed and even causes problems, as described in padraic/mockery#263.
Removing this default allows us to manipulate the object as expected (especially in Mockery tests).
> Removes default on $args in __call

- src/Database/Traits/Validation.php
If the validator doesn't get supplied the primary key name it won't
obey the unique filter on update if the primary key name is different
from `id`.
This way if for some reason primary key is changed via `$primaryKey`
the unique filter will still work by doing `AND WHERE "otherkey" <> 2`
instead of `AND WHERE "id" <> 2`
> Validator obey changed primary key name

- src/Database/Attach/File.php
This should resolve issues where concurrent uploads return the error `mkdir(): file exists.` by taking into consideration the possibility of the race condition.
> Fix "file exists" error on concurrent uploads

- src/Exception/ValidationException.php
As noted in octobercms/october#1253, bad parameters given to ValidationException are ignored and should not be.
> Add parameter type enforcement to ValidationException. closes octobercms/october#1253

- src/Database/Model.php
This fixes an issue in Backend > Settings > Admin > Groups where using
a database table prefix would cause a column not found exception due
to selectRaw() not prepending the prefix to the table name.
> Replace raw select [fixes octobercms/october#1334]

- src/Database/Dongle.php
- src/Database/Migrations/2013_10_01_000001_Db_Deferred_Bindings.php
- src/Database/Migrations/2013_10_01_000001_Db_Files.php
- src/Database/Migrations/2015_10_01_000001_Db_Revisions.php
- src/Database/Schema/Blueprint.php
- src/Scaffold/Console/model/create_table.stub
- src/Support/Facades/Schema.php
Overrides the default Illuminate Blueprint class to implement a fix
that was added in 5.2 but never backported to the LTS version we use.
More info: https://dev.mysql.com/worklog/task/?id=7467
In particular, see F-8 under the Requirements tab.
Also adds a Schema facade with blueprint injector
> The MySQL 5.7.4 change to make strict mode more strict by including `ERROR_FOR_DIVISION_BY_ZERO`, `NO_ZERO_DATE`, and `NO_ZERO_IN_DATE` caused some problems. For example, in MySQL 5.6 with strict mode but not `NO_ZERO_DATE` enabled, `TIMESTAMP` columns can be defined with `DEFAULT '0000-00-00 00:00:00'`. In MySQL 5.7.4 with the same mode settings, strict mode includes the effect of `NO_ZERO_DATE` and `TIMESTAMP` columns cannot be defined with `DEFAULT '0000-00-00 00:00:00'`.
*Source: …
> Make timestamps() create nullable timestamps

- src/Scaffold/Console/CreateCommand.php
- src/Scaffold/Console/command/command.stub
- src/Scaffold/ScaffoldServiceProvider.php
Note: The argument name cannot be named just "command". This name throws
a LogixException saying, the name is already in use. Thus it is named
"command-name" now.
> Add scaffolding command for a console command

- src/Support/helpers.php
When used in loop for example, cause unneeded repetitions to the log.
Problem:
```
for($i = 0; $i < 3; $i++)
{
trace_sql();
\Db::select(…);
}
// Generates 1+2+3 lines of SELECT
```
After fix:
```
for($i = 0; $i < 3; $i++)
{
trace_sql();
\Db::select(…);
}
// Generates 3 lines of SELECT
```
> Multiple call to `trace_sql()` cause log repetitions

- src/Database/Attach/File.php
When I want to send file as email attachment, it would be nice to have `->getContentType()` method available:
```php
$attachment = $record->image; // System\Models\File
Mail::send($template, $templateParameters, function($message) use ($email, $attachment) {
$params = ['as' => $attachment->getFilename(), 'mime' => $attachment->getContentType()];
$message->attach($attachment->getLocalPath(), $params);
$message->to($email);
}
```
> Make getContentType() public

- src/Exception/ExceptionBase.php
This fixes https://github.com/octobercms/october/issues/2274
In some cases the ``file()`` method fails and returns ``false`` which causes array_slice to fail (line 179) and only Error 500 is returned to the user.
```
array_slice() expects parameter 1 to be array, boolean given in ExceptionBase.php:179
```
With this change we ensure that ``fileContent`` property is always an array.
> Ensure that fileContent is an array

- src/Database/Attach/File.php
Delete thumbs should be a public API. In case of any modification to the image, thumbs should be regenerated. I dont see an issue to allow this from a public call.
> Enable public api for ``deleteThumbs()``

- src/Parse/Syntax/FieldParser.php
- src/Parse/Syntax/Parser.php
This PR adds support for ``checkbox`` field to the October syntax parser. This can be very useful when using "Static Pages" plugin where we can allow users to toggle display of certain dynamic layout sections.
Example:
```
{checkbox name="showTitle" label="Show page title"}
<h1>{{ page.title }}</h1>
{/checkbox}
```
Parsing to ``Twig`` is supported, but I don't think that ``Brackets`` parser currently supports conditional statements, so I didn't find a way to support it there.
> Add checkbox support to parser

- src/Database/Traits/Validation.php
When a model uses a different database connection via $connection the validator
would not obey this, making the validator useless for those models.
By adding an optional connection string the validator will use the database connection
provided without interfering with any other code that might directly call the validator
instantiation code.
I made an issue https://github.com/octobercms/october/issues/1580 there, this is my proposed fix basically.
```
class RichIndexPage extends Model
{
/**
* @var string The database table used by the model.
*/
public $table = 'sometable';
public $connection = 'database_two';
use \October\Rain\Database\Traits\Validation;
public $rules = [ 'name' => 'required|unique:sometable,name'];
/**
* @var array Guarded fields
*/
protected $guarded = ['*'];
/**
* @var …
```
> Modified validator to obey connection

- src/Auth/Models/User.php
This fixes the issue presented in octobercms/october#2499 by defaulting permissions to an empty array when the `json_encode` fails on empty data.
> Fixes octobercms/october#2499

- src/Database/Traits/Revisionable.php
**Expected behaviour**
When $revisionableLimit of a model is exceeded, old records should be deleted and new ones created
**Actual behaviour**
Newly created revision is being deleted right after it was created, because of missing _DESC_ parameter in orderBy('id') on line [147](https://github.com/octobercms/library/blob/master/src/Database/Traits/Revisionable.php#L147)
**October build**
385
> Revisionable trait's revisionableCleanUp bugfix

- src/Database/Traits/Sortable.php
Obtain model's primary key value via getKey() method instead property 'id' to ensure coherence with the actual model schema
> [FIX] Use getKey() instead 'id'

- src/Database/MemoryCache.php
- src/Database/QueryBuilder.php
Following discussion in https://github.com/octobercms/october/issues/2640 I went ahead and implemented a simple memory caching system to prevent duplicate queries.
The results are pretty good as you can see below:
Before:
After:
The implementation is quite simple - the results of every database query are saved in an array. And when performing insert/delete/update/truncate operations, the cache for the target table is cleared.
If needed, the cache can also be cleared manually by using:
```php
October\Rain\Database\MemoryCache::instance()->flush();
October\Rain\Database\MemoryCache::instance()->forget('backend_users');
```
Or during query construction:
```php
User::flushMemoryCache()->get(); // flush the cache
User::clearMemoryCache('backend_users')->get(); // forget the cache for the given …
```
> Database memory cache

- src/Halcyon/Model.php
If we return the returned value of the mutator call straight away, that will disable the firing of 
**model.setAttribute** event, and then no third party plugins will be able to implement any kind of post processing logic when an attribute is set with explicit mutators. 
Returning from the mutator call will also break method chaining as intended by returning `$this` at the end of this method.
> Ensured firing of model.setAttribute event when mutator exists

- src/Database/Attach/File.php
Using a filename like "thumb_101_180x300_0_0_crop.jpg" will cause some ad blockers to block the image download (see here also http://stackoverflow.com/questions/17255493/how-to-stop-adblock-plus-blocking-images-in-html-page).
Simply removing the "x" solved the problem in my case (maintains uniqueness and prevents blocking).
> Updated thumb filename to avoid adblockers

- src/Parse/Bracket.php
For more info on what I am exactly trying to do, see this issue: https://github.com/responsiv/campaign-plugin/issues/38
To summarize, I am trying to display a peice of html inside a repeater only if a given variable is set. Actually there is a `parseKeyBooleans()` method that can do what I want, but it doesn't work inside a repeater.
For example, this code works (the parser gives an empty result if the variable is not set):
```HTML
{variable name="image" type="mediafinder" mode="image" label="Image"}{/variable}
{?image}
{/image}
```
But this one doesn't (if the variable is not set, the parser output is `{?image}<img src="http://example.com/storage/app/media/" />{/image}`):
```HTML
{repeater name="blocks" prompt="Add a block"}
{variable name="image" type="mediafinder" mode="image" …
```
> Support condition inside repeater in bracket parser

- src/Html/UrlServiceProvider.php
This is a fix for octobercms/october#3030.
The `forceRootUrl()` method of `Illuminate\Routing\UrlGenerator` sounds like it should include schema as well, but apparently don't (see my comment in the above issue). Not sure if this is the correct way to solve this or if changes should actually be made in `Illuminate\Routing\UrlGenerator`. However I think this is a suitable fix.
> Force schema while using 'force' link policy

- src/Database/Relations/MorphToMany.php
MorphPivot constructor extending Eloquent\Model now, so there is following error:
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::__construct() must be of the type array, object given, called in .../vendor/october/rain/src/Database/Relations/MorphToMany.php on line 164
So i just looked for a new Laravel implementation and made the code exactly the same.
> L5.5 MorphToMany Compatibility

- src/Database/Models/DeferredBinding.php
Fixes octobercms/october#1944 by doing date comparisons in PHP instead of SQL.
> Improve DB platform support for deferred bindings

- src/Database/Attach/Resizer.php
**Problem**: not every photo is correctly rotated, because of bad EXIF reliability. But even if `exif_read_data()` throws some Exception, we can still read EXIF `Orientation` property.
**Related issue**: https://github.com/octobercms/october/issues/1942
**Solution**: Mute `exif_read_data` exceptions and check if there is `Orientation` attribute we need for processing.
**Replication steps**:
1) Use this photo (not mine): [59df79725646d715843413.jpg](https://user-images.githubusercontent.com/374917/31517324-d67ca99c-af9b-11e7-9faa-332d521a77ad.jpg)
2) When put `dd($e)` in previous catch block, it throws `Illegal IFD size` exception: 
3) When put `dd(@exif_read_data($filePath))` we can see, there are some limited data-set we can use: 
Tested with October build 424 on MacOS.
> Fix reading EXIF data for resizer

- src/Parse/Syntax/FieldParser.php
The parser now interprets "true" and "false" values as boolean values instead of string values.
Example:
```
{variable type="text" name="textfield" hidden="false"}{/variable}
```
Previously `hidden="false"` was converted to 
```
[..
"hidden" => "false",
..]
```
Which resulted in the field being hidden, because
`if ("false")` returns to `true`
Now it stores it as
```
[..
"hidden" => false,
..]
```
Which results in the field not being hidden. Same goes for the other boolean field options like commentHtml, readOnly, ignoreTimezone (specific to datepicker), showGutter etc.
> Fix for boolean parameter values

- src/Parse/Syntax/FieldParser.php
- src/Parse/Syntax/Parser.php
This change adds support for the Datepicker field type in the syntax parser. The available datepicker options (mode, format, minDate, maxDate, firstDay) discussed [here](https://octobercms.com/docs/backend/forms#widget-datepicker) are working correctly.
> Added support for datepicker field

- src/Database/Attach/Resizer.php
October build: 428
Php version: 7.0 64bits (tested on Windows and Linux)
- Get an image with a non-black background (I used an uniform gray background of 1200x1600 px)
- Add this image using a `System\Models\File` relation (I used Rainlab Blog plugin)
- Create a cropped thumbnail to a smaller size (I did from twig `myImage.thumb(204, 272, 'crop')`)
- Note that in this particular case, the ratio of the original image and the thumbnail are same, but I suspect that other sizes could be problematic too.
The generated thumbnail get a black border of 1px width on the right side, like this:
The thumbnail should be an uniform gray background without the black border, just like the source image.
By looking at the `October\Rain\Database\Attach\Resizer` class with a debugger, I found this funny …
> Black border on some cropped thumbnails

- src/Database/Builder.php
This ensures that all scopes are applied to the query and is in compliance with the L5.5 paginate() method.
Fixes https://github.com/octobercms/october/issues/3138 .
> Fix pagination total count

- composer.json
- src/Parse/Ini.php
- tests/Parse/IniTest.php
- tests/fixtures/parse/multilines-value.ini
Fixes https://github.com/rainlab/pages-plugin/issues/327
I've added a test case to demonstrate the problem but I could not install composer dependencies on php 7.0.6 (need 7.0.8) so I didn't run it to check.
> Fix escaping of multiline values in INI

- src/Database/Relations/AttachMany.php
- src/Database/Traits/Validation.php
Fix issue from [forum](http://octobercms.com/forum/post/fileupload-validation?page=1#post-23220).
This will allow you to validate individual items from attachMany relation using [Laravel validation of arrays](https://laravel.com/docs/5.5/validation#validating-arrays).
For example
~~~php
use October\Rain\Database\Traits\Validation;
use System\Models\File;
class Gallery extends Model
{
use Validation;
public $attachMany = [
'photos' => File::class
];
public $rules = [
'photos'   => 'required',
'photos.*' => 'image|max:1000|dimensions:min_width=100,min_height=100'
];
/* some other code */
}
~~~
> Add ability to use array validation for attachMany

- tests/Halcyon/SectionParserTest.php
This PR fixes issues with the unit tests introduced here: https://github.com/octobercms/library/commit/0b6c7c63d7128d06ec38a4a31e38f634619952e3
> Fix failing SectionParserTest::testParse

- src/Database/Traits/Sluggable.php
This will allow slugs to be regenerated on save even if the model already exists so that if the slug attribute is missing it will be regenerated.
> Regenerate slugs if missing on existing models.

- src/Database/Relations/DeferOneOrMany.php
We had a manyToMany(belongsToMany) relation, e.g movies, movie_lists.
We used relation behavior to display the form.
There’re almost 1 millions record in movies table.
It costed 30 second when display create form page every time.
So we make a change to enhance the query performance.
Just change the exists query to in query.
It costed 3 second when display create form page.
It might be help to other guy.
> Enhance deferred_bindings table query performance

- tests/Parse/IniTest.php
Fixes INI test which fails on Windows due to broken code not taking EOL characters into account properly.
> Fix test which fails on Windows machines

- src/Cookie/Middleware/EncryptCookies.php
- src/Foundation/Http/Kernel.php
Currently OctoberCMS encrypts all cookies, and thus it always tries to decrypt them on read.
This PR gives developers a chance to specify cookies that should not be decrypted.
Even though `\Illuminate\Cookie\Middleware\EncryptCookies` provides `$except` field and `disableFor` method to specify a list of cookies that shouldn't be decrypted, current implementation of october lib does not make use of them.
With this modification, developer will be able to specify unencrypted cookies in `config/cookie.php` like below.
```
<?php
return [
"unencryptedCookies" => [
"my_cookie",
],
];
```
This is useful when a developer wants to create cookies in frontend to pass data to backend.
> Enable use of unencrypted cookies

- src/Database/Attach/File.php
`pathinfo() !== null` will always return `true`, because if no extension is specified, this method will return an empty string: `""`
This can be verified using the following code:
```php
$path_parts = pathinfo('/path/emptyextension.php', PATHINFO_EXTENSION);
var_dump($path_parts);
$path_parts = pathinfo('/path/noextension', PATHINFO_EXTENSION);
var_dump($path_parts);
```
Added the ability to upload files to the site by link.
To upload a file to a storage and attach to a model - you can use the following code:
```php
$file = new \System\Models\File;
$file->fromLink('https://..../file.jpg');
$user->avatar()->add($file);
```
> Correcting file extension checking in Attach\File, adding the ability to upload a file by URL

- src/Database/Relations/BelongsToMany.php
Related [issue](https://github.com/octobercms/october/issues/3675).
I add new events for BelongsToMany relation
* **relation.afterAttach**
* **relation.afterDetach**
Usage example:
```php
Product::extend(function ($obModel) {
$obModel->bindEvent('relation.afterAttach', function ($sRelationName, $arElementIDList, $arInsertData) {
//$sRelationName == 'category'
//$arElementIDList == [1,3,15]
//$arInsertData = [['product_id' => 10, 'category_id' => 1],['product_id' => 10, 'category_id' => 3],['product_id' => 10, 'category_id' => 15, 'pivot_field' => 'test']];
});
$obModel->bindEvent('relation.afterDetach', function ($sRelationName, $arElementIDList) {
//$sRelationName == 'category'
//$arElementIDList == [1,3,15]
});
});
```
> Add relation.afterAttach, relation.afterDetach events in BelongsToMany relations

- src/Database/Traits/NestedTree.php
This PR adds missing methods `getLeftSibling` and `getRightSibling` to the `NestedTree` trait.
> Added missing getLeftSibling and getRightSibling

- src/Auth/Manager.php
This brings the logout logic more in line with Laravel (see https://github.com/laravel/framework/blob/9f313ce9bb5ad49a06ae78d33fbdd1c92a0e21f6/src/Illuminate/Session/Middleware/AuthenticateSession.php#L92). This also fixes an issue where if you login to a user account, change the locale, logout, login to different user, change locale to different locale, logout, then login to the original user account; the locale from the second user account will be applied.
> Flush entire session on logout, not just auth key

- src/Mail/Mailer.php
In Mailer::queue is $callback optional (`public function queue($view, $data = null, $callback = null, $queue = null)...`) so `buildQueueMailable` have to reflect this. And as well `send` method.
> In Mailer::queue is callback optional

- .travis.yml
- src/Foundation/Bootstrap/LoadTranslation.php
- src/Translation/TranslationServiceProvider.php
- src/Translation/Translator.php
- tests/Translation/TranslatorTest.php
- tests/fixtures/lang/en/lang.php
@LukeTowers Hey, here's the Travis CI setup we talked about in PR octobercms/library#359
Before it's merged to `develop`, you (or someone with access) should activate Travis for the repo `octobercms/library` at https://travis-ci.org/octobercms/library. After merge Travis should pick up the changes and start the build automatically.
Also, tests were failing on current develop version so I've included a fix for the Translation component. Before it depended on the `Event` facade, now it gets the event dispatcher injected with `setEventDispatcher`.
> Travis CI config and a fix for events in Translation component

- src/Router/Helper.php
- tests/Router/RouterHelperTest.php
This is my proposed functionality to leverage for octobercms/october#3358. Since there may be plugin code that makes use of `October\Rain\Router\Helper::parseValues`, I left it untouched and added a `replaceParameters` function that will match a template string for all parameter names and pass those to `parseValues` for the actual replacement.
> Add router helper function to replace parameters without a list of names

- src/Extension/ExtendableTrait.php
- src/Halcyon/Model.php
- tests/Halcyon/ModelTest.php
This is a fix to make dynamic properties work when extending Halcyon Model based classes (like Cms\Classes\Page).
> merge dynamic properties to base attributes

- src/Database/Traits/Validation.php
Call to `fireEvent` returns an array so will never equal `false`. Setting halt parameter to `true` fixes this.
> Not halting validation when returning false from model.beforeValidate

- src/Parse/Assetic/StylesheetMinify.php
While dealing with the `Tabs issue`, found out that there was a css space issue.
Changes:
- Normalize spaces by removing 2 or more space
- Remove newline character before closing bracket to make it cleaner
- Remove `%` - it bugs for keyframes
**storm.css**
**october.css**
**storm.css**
**october.css**
@LukeTowers, could you test this out?
> StylesheetMinify.php Fix

- src/Auth/Manager.php
Removed dependency on `SoftDelete` trait and added `validateUserModel` method to provide the ability to reject a user model.
see https://github.com/octobercms/october/issues/4046 and https://github.com/octobercms/october/pull/4051
> Added validateUserModel method

- src/Extension/ExtendableTrait.php
- tests/Extension/ExtendableTest.php
Adds a function to list all class methods (including those provided by an extension) to a class using the Extendable trait.
> Add get_class_methods() equivalent for extendable classes

- src/Database/Relations/HasMany.php
Pull request #364 created a bug in the `HasMany` relation.
Create a model, for example: `User`
- id
- email
Create a model, for example: `File`
- id
- sender
Have an `HasMany` relation in the `User` model:
```
public $hasMany = [
'files' => [File::class, 'key' => 'sender', 'otherKey' => 'email'],
];
```
Render the partial in the backend:
fields.yaml
```
tabs:
fields:
files:
type: partial
tab: Files
context: update
```
config_relation.yaml
```
files:
label: Files
view:
list: ~/plugins/acme/base/models/files/columns.yaml
recordUrl: acme/base/files/update/:id
emptyMessage: backend::lang.list.no_records
```
_files.htm
```
<?= $this->relationRender('files') ?>
```
The query generated before the fix is:
```
select `email` from `files` where `files`.`sender` = example@example.com and …
```
> Fix hasMany where not using primary key as "key"

- src/Mail/Mailer.php
Moved the mailerInstance parameter to the `Event::listen()` doc rather than the `$mailerInstance->bindEvent()` as the docs were misaligned. Closes octobercms/docs#360
Affects events `mail.prepareSend`, `mail.send`, `mailer.beforeAddContent` and `mailer.addContent`
> Fixed documentation parameter mismatch

- src/Network/Http.php
In a previous commit, this has been changed to a string to ensure the correct argument separator to be set. However, starting from PHP 5.2.0, this disables us from uploading files, as for files an array argument is required. From the docs:
``If value is an array, the Content-Type header will be set to multipart/form-data. As of PHP 5.2.0, value must be an array if files are passed to this option with the @ prefix. As of PHP 5.5.0, the @ prefix is deprecated and files can be sent using CURLFile.
``
See: http://de2.php.net/manual/en/function.curl-setopt.php
> Change POSTFIELDS back to array

- src/Html/FormBuilder.php
See Github Issue: https://github.com/octobercms/october/issues/4253
Please review - have tested it and works fine.
@LukeTowers @w20k
> Inject role="form" to allow accessibility standards.

- src/Database/Traits/Validation.php
- src/Halcyon/Traits/Validation.php
- tests/Database/Traits/ValidationTest.php
- tests/Halcyon/ValidationTraitTest.php
- tests/TestCase.php
Allows for fields to be specified in array notation in a rule array. This functionality will convert the field names to dot notation at the time the validation is run, without affecting the original rules array.
> Convert array notated fields to dot notation on validation

- src/Router/Helper.php
A wildcard parameter can be made optional using the syntax `url = "/blog/:slug?*"`
So this would work:
url/blog
url/blog/category
url/blog/category/subcategory
For using a default value the syntax is `url="/blog/:slug?all*"`
Note: this was already the behaviour when passing a param with ?*, but the parameter was parsed like this:
param name: slug?
value: *
(the optional character wasn't stripped from the parameter name, and the wildcard character was returned as the parameter value)
> Allow optional wildcard parameteres

- src/Scaffold/Console/formwidget/javascript.stub
- src/Scaffold/Console/formwidget/stylesheet.stub
When creating a formwidget with artisan the generated javascript and stylesheet file will show the line 
`This is a sample JavaScript file used by {{ name }}` 
instead of the actual given name i.e.
`This is a sample JavaScript file used by MyFormWidget`
These changes fix this problem
> Removed spaces from stubs so str_replace will place correct values

- src/Halcyon/MemoryCacheManager.php
References octobercms/october#4057.
This implements the true/false/null setting discussed for enabling/disabling the in-memory request-level cache repository, adding the `null` setting that enables the memory cache except when running from the console.
> Disable in-memory cache repository in CLI by default

- src/Foundation/Application.php
- src/Router/RoutingServiceProvider.php
- src/Router/UrlGenerator.php
- src/Support/Facades/Url.php
- src/Support/helpers.php
- tests/Support/UrlGeneratorTest.php
Allows October sites to use the `http_build_url` method, either natively through the PECL HTTP extension, or through the userland polyfill implemented in this PR. This method is a counterpart to the [`parse_url`](https://php.net/parse_url) method provided in PHP - in essence, taking a structured array of URL components and making it a single URL string.
In addition, the PR extends the `Illuminate\Routing\UrlGenerator` class with a new class `October\Rain\Route\UrlGenerator` and uses this as the new endpoint for the `Url` facade.
> Implement "http_build_url" polyfill / wrapper into core

- tests/Halcyon/ModelTest.php
- add test to verify existence of attribute after addDynamicProperty() call
- add comment about post-save test (dynamic properties should not persist to db)
> improve AddDynamicPoperty test

- src/Database/Model.php
This fixes https://github.com/rainlab/translate-plugin/issues/485
> Fix douple decoding of jsonable attributes

- src/Auth/Manager.php
This fix is for https://github.com/octobercms/october/issues/4442
I changed the comparison operator to set the `$user` variable instead.
> Removed extra '=' character

- src/Database/DataFeed.php
It was impossible to get the result because there was no type cast for tagVar in postgres, and was impossible to get count() because bindings with the old query were not added to the final query.
Also, this pull request solves this issues https://github.com/octobercms/october/issues/4252 https://github.com/octobercms/october/issues/4249
> Fix count if have bindings and fix for postgress

- src/Database/Connectors/ConnectionFactory.php
Fixes issue where OctoberCMS throws an error that the class is not found.
> Include InvalidArgumentException class

- src/Network/Http.php
- src/Network/README.md
Http library throws error if you use setOption key as string like **$http->setOption('CURLOPT_RETURNTRANSFER', true);**
> "curl_setopt_array(): Array keys must be CURLOPT constants or equivalent integer values" on line 261 of .../vendor/october/rain/src/Network/Http.php"
Both README and Http.php comments fixed by changing array key to the CURLOPT constant.
> Fixed Error in Comment

- src/Foundation/Console/ClearCompiledCommand.php
Remove the classes compile cache instead of the services cache.
The services cache gets cleared in the parent::handle().
> Clear classes compile cache

- src/Halcyon/Datasource/DbDatasource.php
The basename call here was retrieving only the filename, stripping out the subdirectories when retrieving available paths. This meant that DB results with subdirectories were not corresponding to correct filenames.
Fixes https://github.com/octobercms/october/issues/4642
> Allow subdirectories in DBDatasource filenames

- src/Auth/Manager.php
- src/Cookie/Middleware/EncryptCookies.php
This is based on a security patch that was released by Laravel. We implemented their workaround for the time being, this fixes it properly by disabling cookie serialization all together.
Ref: https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30
> Since this vulnerability is not able to be exploited without access to your application's encryption key, we have chosen to provide a way to re-enable encrypted cookie serialization while you make your application compatible with these changes.
> No longer serialize cookies

- src/Database/Relations/HasOneOrMany.php
In some cases the relationship has already been associated outside this workflow, this change prevents the save events from triggering twice. This works because it mimics Laravel's internals, where if nothing changes on a model, the database is never engaged, otherwise it would produce a nil update query
Replaces https://github.com/octobercms/october/pull/4723. Fixes https://github.com/octobercms/october/issues/4246
> Prevent double saving of models in relation manager widget.

- src/Translation/Translator.php
If you do `trans("hello :where", ['where' => 'world'])`, the `:where` parameter is only substituted if the `hello :where` string is registered in one of the language files. If not, parameter substitutions are not made.
> Allow replacements to be made for unregistered strings

- src/Foundation/Exception/Handler.php
Fixes https://github.com/octobercms/october/issues/3416.
This PR allows to use fully custom responses (Symfony\Component\HttpFoundation\Response) from custom error handlers and fixes the bug mentioned in octobercms/october#3416 and octobercms/october#3127  also allows throwing other Exceptions.
While this is not directly described as a possibility in the docs (https://octobercms.com/docs/services/error-log#exception-handling), where the only example is returning a string which works regardless, I think it's a good thing and also closes octobercms/october#3416 and octobercms/october#3127, which is a bug that occurs when using an error response method that throws an exception.
Checking if the response from a custom handler is a "Response" object fixes the effect that the headers of the …
> Allow using custom or built-in Laravel/Symfony error responses

- src/Foundation/Providers/ArtisanServiceProvider.php
Trim the list of available artisan commands down to those that work.
Commands that are not listed in the array will not be registered,
can not be used on the command and will not appear on the command line when using 'php artisan'.
This PR is a part of an answer to https://github.com/octobercms/docs/issues/394.
I will also submit a small PR for the docs repo, that the 'make' commands from laravel are not supported.
List of disabled command for reference:
* auth
* clear-resets
* db
* seed
* event
* geenerate
* cache
* table
* make
* auth
* command
* event
* exception
* factory
* job
* listener
* mail
* middleware
* migrate
* model
* notification
* policy
* provider
* request
* resource
* rule
* seeder
* test
* migrate
* fresh
* install
* refresh
* reset
* rollback
* status
* notifications …
> Trim the list of available artisan commands

- src/Translation/Translator.php
The current implementation of the translator is not compatible with the interface.
The translator interface requires 3 parameters for method `trans`
```php
public function trans($key, array $replace = [], $locale = null);
```
The current implementation has 4 parameters.
```php
public function trans($id, array $parameters = [], $domain = 'messages', $locale = null)
{
return $this->get($id, $parameters, $locale);
}
```
If I resolve the translator interface I can't set the locale, because it will set the domain parameter (which isn't used) instead of the locale parameter.
For example this will not work:
```php
/** @var Illuminate\Contracts\Translation\Translator $translator */
$translator = resolve(Illuminate\Contracts\Translation\Translator::class);
$translator->trans('my_key', [], 'nl'); …
```
> Make translator implementation compatible with translator interface

- src/Mail/Mailer.php
The [docs stipulate](https://octobercms.com/docs/services/mail#queueing-mail) using a string for the view parameter when using Mail. When a string is given, the `October\Rain\Mail\Mailer` class is converting the string into a `Mailable` object to pass through Laravel's mail functionality. This `Mailable` object is not being populated with the queue name, and is instead trying to use the queue name as the manager that is passed through to the Mailable object. This is failing when the Mailable is added to the queue, therefore breaking the `Mail::queueOn()` and `Mail::laterOn()` functions.
This fix takes the queue name and injects it into the `Mailable` object, then sets the queue parameter to `null` so that the default QueueManager is used to create the queued job.
Fixes …
> Inject queue name into auto-created Mailables.

- src/Parse/Assetic/Less/lib/Less/Tree/Import.php
Fixes running the `php artisan october:util compile assets` command on PHP 7.4
Discussion here: https://github.com/octobercms/october/issues/4797#issuecomment-576020722
> Check current file info before using it

- src/Extension/ExtendableTrait.php
- Include dynamic properties in propertyExists() method checks.
- Bail out when adding an existing dynamic property in addDynamicProperty()
> fix propertyExists() and addDynamicProperty() methods of ExtendableTrait

- src/Assetic/Filter/ScssphpFilter.php
- src/Events/Dispatcher.php
Hi, this should fixe the CS error.
> Code sniffer

- src/Database/Traits/Validation.php
Creating a custom validation rule starting with *unique* and adding it to your model results in unintended behaviour when updating the model, as your custom role is overridden with the default *unique* rule.
For example:
```php
Validator::extendDependent('unique_with', function (string $attribute, $value, array $parameters, \Illuminate\Validation\Validator $validator) {
dd('hi');
});
class MyModel extends Model
{
use \October\Rain\Database\Traits\Validation;
public $table = 'my_table';
public $rules = [
'key' => 'unique_with:foo,bar',
];
}
```
The `dd()` will never execute with this rule on your model, because these lines 
https://github.com/octobercms/library/blob/bb6d88a0f8b33b535de71101ea281245ebe7267c/src/Database/Traits/Validation.php#L379-L381
replace our rule with
> …
> Fix override of custom validation rules starting with 'unique'

- src/Database/Attach/File.php
This change aims to guess file extension from MIME type if file is being uploaded without file extension. The guessed extension is then added to the generated filename.
Some contextual explanation: 
**Why would a file be uploaded without extension?**
It's the case for raw blob files. For instance, in my app I let the user choose a image file and then allow her/him to do some basic editing (like cropping) client-side. Thus, when uploading, I'm no longer uploading the raw file, but a blob file that don't have a filename and thus doesn't have any extension.
**Why storing file without extension is an issue?**
This can break other October features. For instance, the issue I had when uploading blob images, was that the getThumb function silently failed (because it didn't consider images without …
> Guess extension for uploaded files if missing

- src/Config/Repository.php
Removed unused `$segments` and add typehint to callback to fix method not found warnings:
> Cleanup config repository

- src/Assetic/Filter/ScssphpFilter.php
Previously, this method would pass the same loadPath to all assets down the hierarchy, which would result in any relative paths not being able to be found. This change will take the current directory of the current asset and use that as a base for all child assets.
Will need to test this with a few SCSS-based themes.
> Pass current SCSS asset path down to children to use as new root path.

- src/Database/Models/Revision.php
This avoid `InvalidArgumentException: Data missing in vendor/nesbot/carbon/src/Carbon/Carbon.php:917` when a revisioned date field as `old_value` or `new_value` empty.
This commit implement same check that the Laravel `getAttributeValue` method use before calling `asDateTime`: [/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L353-L354](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L353-L354)
> Don't cast Revision old/new values to DateTime when value is empty

- composer.json
Laravel updated Tinker to 2.0 as of version 6.8.0. This PR is to keep the version October uses in line with Laravel.
> Update Laravel Tinker to 2.0

- src/Database/Traits/Validation.php
- tests/Database/Traits/ValidationTest.php
`Validation::processValidationUniqueRule()` ignores custom connection name when modifying rule that requires database lookup.
> Fix "unique" validation rule when used with external database

- src/Database/Relations/BelongsToMany.php
When calling `$model->someBelongsToManyRelation()->createMany([...])` a deferred binding is created in the database with session key 0. Calling `$model->save()` after this does not commit the deferred binding. A deferred binding is created even when `$model` exists in the database. This issue only affects belongsToMany relations from what I can tell.
I've created a simple plugin [here](https://github.com/Flynsarmy/oc-baddefer-plugin) to replicate the issue.
`createMany()` is called through the Illuminate file *vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php*.
It loops through each passed array calling `$this->create($record, (array) ($joinings[$key] ?? []), false);` - notice that third argument passed (the one for sessionKey) is `false`.
`create()` is …
> Support session keys passed through createMany()

- src/Translation/Translator.php
October 466 introduced a regression in our install.
The transChoice filter stopped working (the ":count" placeholder is no longer replaced on strings).
Not sure what caused the regression, but copying this line from Laravel's Translator implementation fixes the issue.
> Fix transChoice broken with October build 466

- src/Network/Http.php
My editor barfed when I tried to pass an anonymous function here, and… the phpdoc expected array. While it the callable $options _could_ be an array, if it were using the callable literal style [$object, 'method'], it's more likely to be passed an anonymous function (like described in the example)
> Http docblock asks for an array, when really what it wants is a callable
