src/Network/Http.php

https://github.com/octobercms/october/issues/817

Disable CURLOPT_FOLLOWLOCATION

---

src/Database/Model.php

Keep up with Laravel 5.0.6

---

src/Router/Helper.php

After your edit and pushed to develop branch.

fix router helper parseValues for objects

---

src/Database/Traits/NestedTree.php

by replacing them with Emitter trait ones, related to https://github.com/octobercms/library/pull/82 (issue https://github.com/octobercms/library/issues/78)

fixes static, untestable event bindings 

---

src/Database/Traits/Validation.php

handles translation strings for custom messages and attribute names

Feature: adds translation string parsing for Validation trait

---

src/Database/Attach/Resizer.php

Add support for uppercased extensions - e.g. JPEG

Add support for uppercased extensions

---

src/Html/Helper.php

Fixes ``<a href="java<script>script: alert('test');">asas</a>``

Fix XSS flaw

---

src/Database/Traits/NestedTree.php

fixes event names in nested tree, my fault, borked in previous PR

---

src/Database/Traits/Validation.php

but dont remove native validation events
updated to agreed version.
references issue #78

fix validation trait static event bindings 

---

src/Network/Http.php

added open_basedir detection for circumventing CURLOPT_FOLLOWLOCATION

---

src/Database/Attach/File.php

I'm addressing this issue for OctoberCMS:
octobercms/october#1143
I added outputThumb and restructured some redundant code on the way.
I'm preparing a pull request for the FileUpload FormWidget as well, but wanted to get some feedback first.

Extending the Attach Filemodel for Thumb output

---

src/Database/Model.php

Including https://github.com/laravelbook/ardent/pull/227 from IRC conversation.

fixed morphTo eager loading with ardent PR 227 solution

---

src/Database/Traits/Hashable.php

Similar to #122 we shouldn't allow adding of the same hashable value more than once.

Don't allow duplicate hashable values

---

src/Support/Facades/Block.php

Fix docblock resolve typo

---

src/Database/Attach/Resizer.php

Minor fix on Resizer.

---

src/Scaffold/Console/CreatePlugin.php

Fix create:plugin command.

---

src/Filesystem/Zip.php

(been a couple of years since using Github / pull requests, so apologies if this was not done correctly)

Ensure destination exists before extracting zip

---

src/Database/Relations/MorphMany.php

add morphMany support for
[https://github.com/octobercms/october/pull/2128] pull-request

morphMany support

---

src/Html/FormBuilder.php

Fix getting zero value to form input. Zero is also value. When I have zero value in my database, form looks like that:
Before fix: `<input name="test" value="">`
After fix: `<input name="test" value="0">`.

Fix getting zero value

---

src/Network/Http.php

Network: fix auth

---

composer.json
src/Parse/Assetic/LessCompiler.php
src/Parse/Assetic/ScssCompiler.php

https://github.com/octobercms/library/pull/220
this should say everything

Change asset compiling

---

src/Database/Attach/Resizer.php

addresses https://github.com/octobercms/october/issues/1942

Add EXIF rotation to Resizer

---

src/Html/HtmlBuilder.php

Resubmits @reg2005's commit in PR octobercms/library#224 to the correct branch

Add unicode support to the HtmlBuilder limit method

---

src/Database/Builder.php

This fixes searching in list filters under Postgres database.
Same issue as here: https://github.com/octobercms/october/pull/2092

Fix searching in non text fields under Postgres (filters)

---

src/Database/Attach/File.php

This is the easiest implementation possible, however it requires a temporary file to be created. It can be discussed, if there is a need to delete the file afterwards explicitly.

Add fromData() method

---

src/Scaffold/Console/controller/_list_toolbar.stub
src/Scaffold/Console/controller/config_list.stub

Recreated pull request to because I messed up first time round

Set checkboxes true create controller and add delete button onto backend list

---

src/Support/ClassLoader.php

This is in relation to this issue:
https://github.com/octobercms/october/issues/2920

Change file output in Class Loader

---

src/Database/Attach/File.php
src/Database/Attach/Resizer.php

This adds interlacing to png/gif/jpeg (webp excluded cause idk if it uses it)

Add Interlacing

---

src/Database/Attach/Resizer.php

Been wanting to do this for a while, webp speed is good too.
Wanna start implementing interlacing eventually.

Add WEBP Support

---

src/Database/Attach/File.php

File uploads forgot about that

Add WEBP Support #2

---

src/Database/Concerns/HasRelationships.php

Method forceSchema does not exist

---

src/Events/Dispatcher.php

Copied from:
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Events/Dispatcher.php#L269

Fix: [L5.5] Cannot broadcast an event #3107

---

src/Support/Traits/Singleton.php

Pretty straightforward. Discussion is in octobercms/october#3208.

Allow singleton instances to be reset

---

src/Database/Model.php

Unexpected type of array when attempting to save attribute "%s", try adding it to the $jsonable property.

Updated jsonable exception message

---

src/Database/Model.php

Solving octobercms/october#3399

Update asDateTime to reflect laravel/framework

---

src/Database/Model.php
tests/Database/ModelAddersTest.php

Closes https://github.com/octobercms/october/issues/3407

Implement adder for model attribute casting

---

src/Mail/Mailable.php

fixing octobercms/october#3384

Mailable sets the subject of the message

---

src/Filesystem/Definitions.php

Adds .ppt, .pptx MS Power Point document file extensions

Add more document extensions

---

tests/Halcyon/SectionParserTest.php

Fix for call to undefined method SectionParserTest::assertHasKey()
assertHasKey changed to assertArrayHasKey

Error in SectionParserTest

---

src/Database/Attach/File.php
src/Database/Traits/DeferredBinding.php
src/Extension/ExtendableTrait.php
src/Extension/README.md
src/Mail/Mailer.php

Fix spelling / typos

---

src/Extension/ExtensionTrait.php

extensionIsHiddenField should be extensionIsHiddenMethod

Corrects typo in ExtensionTrait

---

src/Filesystem/Definitions.php

Adds .xml as valid and publicly accessible extensions type

Add .xml extension

---

src/Events/Dispatcher.php
tests/Events/DispatcherTest.php

Fixes issue octobercms/october#3104
This PR includes a test that checks if the job class really exists. 
Credit to @vdomah for providing the original solution.

Fix queued event handler classname

---

src/Auth/Manager.php

This is my proposed fix for https://github.com/octobercms/october/issues/3999

Added manual deleted_at check to auth manager

---

src/Parse/Assetic/StylesheetMinify.php

Related to:
- https://github.com/octobercms/october/pull/4038
- https://github.com/octobercms/october/issues/4040

Reverted newlines and zeros

---

.travis.yml
src/Parse/Yaml.php

Should handle https://github.com/octobercms/october/issues/4073

Add YAML file being parsed to syntax error message

---

src/Network/Http.php

Reverts octobercms/library#380. @alxy you need to figure out the issue with the updating being broken and then submit a fully tested PR if you want this changed.

Revert "Change POSTFIELDS back to array"

---

src/Database/Traits/Sluggable.php
tests/Database/Traits/SluggableTest.php

fix https://github.com/octobercms/october/issues/4192
@LukeTowers here it is :)

Add withTrashed to prevent softDelete slug duplication

---

src/Database/Relations/HasMany.php

Revert 'HasMany memory performance solution'

---

src/Halcyon/Datasource/Datasource.php
src/Halcyon/Datasource/DatasourceInterface.php
src/Halcyon/Datasource/DbDatasource.php
src/Halcyon/Datasource/FileDatasource.php
src/Halcyon/Model.php

Related: octobercms/october#3908

Halcyon DbDatasource

---

src/Database/Attach/File.php

Improves File handling logic by running file commands on the disk that the file is on and centralizes the logic to generate the diskPath in one method.

Various improvements to File handling logic

---

src/Scaffold/Console/model/create_table.stub

Made the stub conformant with [OctoberCMS' coding standard](https://github.com/octobercms/october/blob/develop/phpcs.xml).

Coding Style Updated

---

src/Html/FormBuilder.php

As pre conversation: https://github.com/octobercms/october/issues/4253#issuecomment-525032718

Turn off default role-form

---

src/Auth/Manager.php
src/Cookie/Middleware/EncryptCookies.php

Leaving this as a WIP PR until @daftspunk has finished his changes and the core team has discussed them.

[WIP] Changes by @daftspunk

---

src/Database/Model.php
src/Halcyon/Model.php

- fix wrong argument provided to fireEvent() call ($attr -> $value)
- add event documentation comments

add event documentation comments;

---

src/Config/ConfigServiceProvider.php
src/Foundation/Bootstrap/LoadConfiguration.php

This allows the config path to be changed dynamically, ie. for tests.

Use "path.config" app variable for loading configuration

---

src/Html/BlockBuilder.php

Add throws docblocks to blockbuilder

Add throws docblocks to blockbuilder

---

src/Config/FileLoader.php

Add throws docblocks and fix code style issues

Add throws docblocks to file loader

---

src/Database/Behaviors/Purgeable.php

prevent conflict with SimpleTree/NestedTree traits

rename parent property

---

src/Database/Builder.php

- Remove unused import
- Add builder typehint to callbacks
- Fix code style

Cleanup database builder

---

src/Support/Facades/Block.php
src/Support/Facades/Config.php
src/Support/Facades/DbDongle.php
src/Support/Facades/File.php
src/Support/Facades/Flash.php
src/Support/Facades/Form.php
src/Support/Facades/Html.php
src/Support/Facades/Http.php
src/Support/Facades/Ini.php
src/Support/Facades/Markdown.php
src/Support/Facades/Schema.php
src/Support/Facades/Str.php
src/Support/Facades/Twig.php
src/Support/Facades/Url.php
src/Support/Facades/Yaml.php

Add typehinting to schema facade like laravel does.
From this:
To this:

Add static method typehints to schema facade

---

src/Database/DataFeed.php

- Remove extract so we don't have magic variables.
- Add docblocks

Cleanup data feed

---

src/Scaffold/Console/controller/create.stub
src/Scaffold/Console/controller/update.stub

Related: https://github.com/octobercms/october/pull/5088

Add data-request-validate to the controller scaffolding

---

tests/Html/HtmlBuilderTest.php

Refs https://github.com/octobercms/october/issues/5153#issuecomment-660548324

Added HtmlBuilder test with umlauts to test for proper encoding
